/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


import type { Configuration } from '../configuration';
import type { AxiosPromise, AxiosInstance, RawAxiosRequestConfig } from 'axios';
import globalAxios from 'axios';
// Some imports not used depending on template conditions
// @ts-ignore
import { DUMMY_BASE_URL, assertParamExists, setApiKeyToObject, setBasicAuthToObject, setBearerAuthToObject, setOAuthToObject, setSearchParams, serializeDataIfNeeded, toPathString, createRequestFunction } from '../common';
// @ts-ignore
import { BASE_PATH, COLLECTION_FORMATS, type RequestArgs, BaseAPI, RequiredError, operationServerMap } from '../base';
// @ts-ignore
import type { ApiAddTaskRequest } from '../model';
// @ts-ignore
import type { ApiAddTaskResponse } from '../model';
// @ts-ignore
import type { ApiGetTaskListResponse } from '../model';
/**
 * TaskCURDApi - axios parameter creator
 * @export
 */
export const TaskCURDApiAxiosParamCreator = function (configuration?: Configuration) {
    return {
        /**
         * --------------------------------------------------  tbl : task
         * @param {ApiAddTaskRequest} apiAddTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDAddTask: async (apiAddTaskRequest: ApiAddTaskRequest, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            // verify required parameter 'apiAddTaskRequest' is not null or undefined
            assertParamExists('taskCURDAddTask', 'apiAddTaskRequest', apiAddTaskRequest)
            const localVarPath = `/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'POST', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;


    
            localVarHeaderParameter['Content-Type'] = 'application/json';

            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};
            localVarRequestOptions.data = serializeDataIfNeeded(apiAddTaskRequest, localVarRequestOptions, configuration)

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDDelTaskByIDList: async (iDList?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'DELETE', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (iDList) {
                localVarQueryParameter['iDList'] = iDList;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDGetTaskList: async (iDList?: Array<number>, options: RawAxiosRequestConfig = {}): Promise<RequestArgs> => {
            const localVarPath = `/task`;
            // use dummy base URL string because the URL constructor only accepts absolute URLs.
            const localVarUrlObj = new URL(localVarPath, DUMMY_BASE_URL);
            let baseOptions;
            if (configuration) {
                baseOptions = configuration.baseOptions;
            }

            const localVarRequestOptions = { method: 'GET', ...baseOptions, ...options};
            const localVarHeaderParameter = {} as any;
            const localVarQueryParameter = {} as any;

            if (iDList) {
                localVarQueryParameter['iDList'] = iDList;
            }


    
            setSearchParams(localVarUrlObj, localVarQueryParameter);
            let headersFromBaseOptions = baseOptions && baseOptions.headers ? baseOptions.headers : {};
            localVarRequestOptions.headers = {...localVarHeaderParameter, ...headersFromBaseOptions, ...options.headers};

            return {
                url: toPathString(localVarUrlObj),
                options: localVarRequestOptions,
            };
        },
    }
};

/**
 * TaskCURDApi - functional programming interface
 * @export
 */
export const TaskCURDApiFp = function(configuration?: Configuration) {
    const localVarAxiosParamCreator = TaskCURDApiAxiosParamCreator(configuration)
    return {
        /**
         * --------------------------------------------------  tbl : task
         * @param {ApiAddTaskRequest} apiAddTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskCURDAddTask(apiAddTaskRequest: ApiAddTaskRequest, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiAddTaskResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskCURDAddTask(apiAddTaskRequest, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskCURDApi.taskCURDAddTask']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskCURDDelTaskByIDList(iDList?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<object>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskCURDDelTaskByIDList(iDList, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskCURDApi.taskCURDDelTaskByIDList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        async taskCURDGetTaskList(iDList?: Array<number>, options?: RawAxiosRequestConfig): Promise<(axios?: AxiosInstance, basePath?: string) => AxiosPromise<ApiGetTaskListResponse>> {
            const localVarAxiosArgs = await localVarAxiosParamCreator.taskCURDGetTaskList(iDList, options);
            const localVarOperationServerIndex = configuration?.serverIndex ?? 0;
            const localVarOperationServerBasePath = operationServerMap['TaskCURDApi.taskCURDGetTaskList']?.[localVarOperationServerIndex]?.url;
            return (axios, basePath) => createRequestFunction(localVarAxiosArgs, globalAxios, BASE_PATH, configuration)(axios, localVarOperationServerBasePath || basePath);
        },
    }
};

/**
 * TaskCURDApi - factory interface
 * @export
 */
export const TaskCURDApiFactory = function (configuration?: Configuration, basePath?: string, axios?: AxiosInstance) {
    const localVarFp = TaskCURDApiFp(configuration)
    return {
        /**
         * --------------------------------------------------  tbl : task
         * @param {ApiAddTaskRequest} apiAddTaskRequest 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDAddTask(apiAddTaskRequest: ApiAddTaskRequest, options?: RawAxiosRequestConfig): AxiosPromise<ApiAddTaskResponse> {
            return localVarFp.taskCURDAddTask(apiAddTaskRequest, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDDelTaskByIDList(iDList?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<object> {
            return localVarFp.taskCURDDelTaskByIDList(iDList, options).then((request) => request(axios, basePath));
        },
        /**
         * 
         * @param {Array<number>} [iDList] 
         * @param {*} [options] Override http request option.
         * @throws {RequiredError}
         */
        taskCURDGetTaskList(iDList?: Array<number>, options?: RawAxiosRequestConfig): AxiosPromise<ApiGetTaskListResponse> {
            return localVarFp.taskCURDGetTaskList(iDList, options).then((request) => request(axios, basePath));
        },
    };
};

/**
 * TaskCURDApi - object-oriented interface
 * @export
 * @class TaskCURDApi
 * @extends {BaseAPI}
 */
export class TaskCURDApi extends BaseAPI {
    /**
     * --------------------------------------------------  tbl : task
     * @param {ApiAddTaskRequest} apiAddTaskRequest 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskCURDApi
     */
    public taskCURDAddTask(apiAddTaskRequest: ApiAddTaskRequest, options?: RawAxiosRequestConfig) {
        return TaskCURDApiFp(this.configuration).taskCURDAddTask(apiAddTaskRequest, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<number>} [iDList] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskCURDApi
     */
    public taskCURDDelTaskByIDList(iDList?: Array<number>, options?: RawAxiosRequestConfig) {
        return TaskCURDApiFp(this.configuration).taskCURDDelTaskByIDList(iDList, options).then((request) => request(this.axios, this.basePath));
    }

    /**
     * 
     * @param {Array<number>} [iDList] 
     * @param {*} [options] Override http request option.
     * @throws {RequiredError}
     * @memberof TaskCURDApi
     */
    public taskCURDGetTaskList(iDList?: Array<number>, options?: RawAxiosRequestConfig) {
        return TaskCURDApiFp(this.configuration).taskCURDGetTaskList(iDList, options).then((request) => request(this.axios, this.basePath));
    }
}

