/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * --------------------------------------------------  tbl : task
 * @export
 * @interface ApiTaskInfo
 */
export interface ApiTaskInfo {
    /**
     * 
     * @type {number}
     * @memberof ApiTaskInfo
     */
    'iD'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskInfo
     */
    'parentID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'task'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskInfo
     */
    'status'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiTaskInfo
     */
    'estimate'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'start'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'end'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'desc'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'metadata'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiTaskInfo
     */
    'createTime'?: string;
}

