/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * 
 * @export
 * @interface ApiEditUserNameRequest
 */
export interface ApiEditUserNameRequest {
    /**
     * 
     * @type {number}
     * @memberof ApiEditUserNameRequest
     */
    'ID'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiEditUserNameRequest
     */
    'userName'?: string;
}

