/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * --------------------------------------------------  tbl : course_swap_request
 * @export
 * @interface ApiCourseSwapRequestInfo
 */
export interface ApiCourseSwapRequestInfo {
    /**
     * 
     * @type {number}
     * @memberof ApiCourseSwapRequestInfo
     */
    'iD'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'srcTeacher'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'srcDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiCourseSwapRequestInfo
     */
    'srcCourseNum'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'srcCourse'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'srcClass'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'dstTeacher'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'dstDate'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiCourseSwapRequestInfo
     */
    'dstCourseNum'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'dstCourse'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'dstClass'?: string;
    /**
     * 
     * @type {string}
     * @memberof ApiCourseSwapRequestInfo
     */
    'createTime'?: string;
    /**
     * 
     * @type {number}
     * @memberof ApiCourseSwapRequestInfo
     */
    'status'?: number;
}

