/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * --------------------------------------------------  tbl : user_dept_assoc
 * @export
 * @interface ApiUserDeptAssocInfo
 */
export interface ApiUserDeptAssocInfo {
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeptAssocInfo
     */
    'userID'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeptAssocInfo
     */
    'deptID'?: number;
    /**
     * 
     * @type {number}
     * @memberof ApiUserDeptAssocInfo
     */
    'jobID'?: number;
}

