/* tslint:disable */
/* eslint-disable */
/**
 * 
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.0.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */



/**
 * --------------------------------------------------  tbl : abandon_code
 * @export
 * @interface ApiAbandonCodeInfo
 */
export interface ApiAbandonCodeInfo {
    /**
     * MARK REPLACE PB COL START 替换内容，所有字段
     * @type {number}
     * @memberof ApiAbandonCodeInfo
     */
    'idx1'?: number;
    /**
     * 
     * @type {string}
     * @memberof ApiAbandonCodeInfo
     */
    'col1'?: string;
}

